version: '3'
services:
  s10:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "6080:6080"
      - "5554:5554"
      - "5555:5555"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm
  s9:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6081:6080
      - 5556:5554
      - 5557:5555
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S9
      - WEB_VNC=true    
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm